# Generated by Django 3.2.9 on 2021-11-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20211118_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='is_main',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
