# Generated by Django 3.2.9 on 2021-11-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_scope_is_main'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scope',
            new_name='ArticleTag',
        ),
        migrations.RemoveField(
            model_name='article',
            name='scopes',
        ),
        migrations.AddField(
            model_name='article',
            name='article_tag',
            field=models.ManyToManyField(related_name='scopes', through='articles.ArticleTag', to='articles.Tag'),
        ),
    ]
